export const TEST_IDS = {
  LOADING: 'LOADING',
  FAVICON: 'FAVICON',
  FAVICON_SKELETON: 'FAVICON_SKELETON',
  FAVICON_FALLBACK: 'FAVICON_FALLBACK',
  THUMBNAIL: 'THUMBNAIL',
  THUMBNAIL_SKELETON: 'THUMBNAIL_SKELETON',
  THUMBNAIL_FALLBACK: 'THUMBNAIL_FALLBACK',
  AUTHOR: 'AUTHOR',
  ORIGIN: 'PUBLISHER',
  ANCHOR_ELEMENT: 'ANCHOR_ELEMENT',
  TITLE: 'TITLE',
  TITLE_SKELETON: 'TITLE_SKELETON',
  DESCRIPTION: 'DESCRIPTION',
};

export function byTestId(testId: string) {
  return `[data-testid="${testId}"]`;
}
